services:
  - type: web
    name: lebas-shoii-bot
    env: python
    region: frankfurt  # می‌تونی مثلا oregon یا singapore هم بذاری
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
